"use client";

import { FormEvent, useEffect, useState } from "react";
import { api } from "@/lib/api-client";
import type { GeoPlace, Place, Trip } from "@/lib/types";
import { MapCanvas } from "@/components/map/MapCanvas";
import { useMapEditorStore } from "@/stores/map-editor-store";

export default function TripEditor({ params }: { params: Promise<{ tripId: string }> }) {
  const [tripId, setTripId] = useState<string | null>(null); const [trip, setTrip] = useState<Trip | null>(null); const [places, setPlaces] = useState<Place[]>([]); const [results, setResults] = useState<GeoPlace[]>([]); const [message, setMessage] = useState<string | null>(null); const selectedPlaceId = useMapEditorStore((state) => state.selectedPlaceId); const selectPlace = useMapEditorStore((state) => state.selectPlace);
  useEffect(() => { params.then(({ tripId: id }) => setTripId(id)); }, [params]);
  async function load() { if (!tripId) return; try { const [nextTrip, nextPlaces] = await Promise.all([api<Trip>(`/trips/${tripId}`), api<Place[]>(`/trips/${tripId}/places`)]); setTrip(nextTrip); setPlaces(nextPlaces); } catch { location.assign("/login"); } }
  useEffect(() => { load(); }, [tripId]);
  async function search(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const keyword = String(new FormData(event.currentTarget).get("keyword")); if (keyword.trim().length < 2) return setMessage("至少输入两个字符"); try { setResults(await api<GeoPlace[]>(`/geo/places/search?keyword=${encodeURIComponent(keyword)}&city=${encodeURIComponent(trip?.destination_city ?? "")}`)); setMessage(null); } catch (exception) { setMessage(exception instanceof Error ? exception.message : "搜索失败"); } }
  async function addResult(result: GeoPlace) { if (!tripId) return; try { await api(`/trips/${tripId}/places`, { method: "POST", body: JSON.stringify({ provider_place_id: result.provider_place_id }) }); await load(); } catch (exception) { setMessage(exception instanceof Error ? exception.message : "添加失败"); } }
  async function addManual(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!tripId) return; const data = new FormData(event.currentTarget); try { await api(`/trips/${tripId}/places`, { method: "POST", body: JSON.stringify({ name: data.get("name"), longitude: Number(data.get("longitude")), latitude: Number(data.get("latitude")), category: data.get("category") }) }); event.currentTarget.reset(); await load(); } catch (exception) { setMessage(exception instanceof Error ? exception.message : "添加失败"); } }
  async function removePlace(placeId: string) { if (!tripId) return; await api(`/trips/${tripId}/places/${placeId}`, { method: "DELETE" }); if (selectedPlaceId === placeId) selectPlace(null); await load(); }
  return <main className="editor"><header><div><a href="/trips">← 返回旅行</a><h1>{trip?.name ?? "加载中…"}</h1><p>{trip?.destination_city}</p></div></header><aside className="search-panel"><form onSubmit={search}><input name="keyword" placeholder="搜索景点、酒店、餐厅…" /><button>搜索</button></form>{message && <p className="error">{message}</p>}<div className="results">{results.map((result) => <article key={result.provider_place_id}><strong>{result.name}</strong><span>{result.address}</span><button onClick={() => addResult(result)}>添加到地图</button></article>)}</div><details><summary>手动添加地点</summary><form onSubmit={addManual}><input name="name" placeholder="名称" required /><input name="longitude" type="number" step="any" placeholder="经度" required /><input name="latitude" type="number" step="any" placeholder="纬度" required /><select name="category"><option value="other">其他</option><option value="attraction">景点</option><option value="hotel">酒店</option><option value="restaurant">餐厅</option></select><button>添加</button></form></details></aside><section className="map-area"><MapCanvas places={places} /></section><aside className="places-panel"><h2>地图地点</h2>{places.map((place) => <article className={selectedPlaceId === place.id ? "selected" : ""} key={place.id} onClick={() => selectPlace(place.id)}><strong>{place.name}</strong><span>{place.category} · {place.address ?? "手动地点"}</span><button onClick={(event) => { event.stopPropagation(); removePlace(place.id); }}>删除</button></article>)}{!places.length && <p>从左侧搜索并添加地点。</p>}</aside></main>;
}
